---
# Source: kyverno-policies/templates/check-private-compositions.tpl.yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-private-compositions
spec:
  background: false
  rules:
  - name: check-private-compositions
    context:
    - name: privateCompositions
      apiCall:
        jmesPath: items[?status.conditions[?type!='Offered']].[spec.names.kind][]
        method: GET
        urlPath: /apis/apiextensions.crossplane.io/v1/compositeresourcedefinitions
    match:
      any:
      - resources:
          kinds:
          - acme.com/*/*
    preconditions:
      all:
      - key: "{{ request.object.kind }}"
        operator: In
        value: "{{ privateCompositions }}"
    validate:
      allowExistingViolations: true
      deny:
        conditions:
          any:
          - key: "{{  request.userInfo.username }}"
            operator: AllNotIn
            value:
            - system:serviceaccount:crossplane-system:crossplane
            - system:serviceaccount:velero:velero
      message: Only allowed controllers can deploy private compositions
  validationFailureAction: Enforce
---
# Source: kyverno-policies/templates/check-private-crossplane-resources.tpl.yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-private-crossplane-resources
spec:
  background: false
  rules:
  - name: check-private-crossplane-resources
    context:
      - name: crossplaneApis
        apiCall:
          jmesPath: items[?regex_match('(crossplane|upbound).io$', metadata.name)].metadata.name
          method: GET
          urlPath: /apis/apiextensions.k8s.io/v1/customresourcedefinitions
    match:
      any:
      - resources:
          kinds: "{{ crossplaneApis }}"
    celPreconditions:
      - name: Bypass allowed resources
        expression: >-
          request.resource.kind.group == 'pkg.crossplane.io' &&
          request.resource.kind.kind in ["ProviderConfig", "Usage"]
    validate:
      allowExistingViolations: true
      message: Only Crossplane controller can deploy provider-specific resources
      deny:
        conditions:
          any:
          - key: "{{ request.userInfo.username }}"
            operator: AllNotIn
            value:
            - system:serviceaccount:crossplane-system:crossplane
            - system:serviceaccount:velero:velero
  validationFailureAction: Enforce
